# Generated by Django 4.0.2 on 2022-11-30 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_solarpanel_is_on_tv_is_on_windturbine_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_consumption',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='last_production',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userconsumption',
            name='consuming',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproduction',
            name='producing',
            field=models.IntegerField(default=0),
        ),
    ]
