# Generated by Django 4.0.2 on 2022-12-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userproduction_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windturbine',
            old_name='producing_per_minute',
            new_name='production_per_minute',
        ),
    ]
