# Generated by Django 4.0.2 on 2022-12-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_producing_per_minute_windturbine_production_per_minute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarpanel',
            old_name='producing_per_minute',
            new_name='production_per_minute',
        ),
    ]
