# Generated by Django 4.0.2 on 2022-12-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_producing_per_minute_solarpanel_production_per_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SOLAR_PANEL', 'solar_panel'), ('WIND_TURBINE', 'wind_turbine')], default='SOLAR_PANEL', max_length=20)),
                ('consumption_per_minute', models.IntegerField(default=10)),
                ('is_on', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProducingObject', to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_per_minute', models.IntegerField(default=10)),
                ('is_on', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Heating', to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Cooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_per_minute', models.IntegerField(default=10)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cooling', to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HEATING', 'heating'), ('COOLING', 'cooling'), ('TV', 'tv'), ('LIGHTING', 'lighting'), ('WASHER', 'washer'), ('DRYER', 'dryer'), ('REFREGIRATOR', 'refregirator')], default='HEATING', max_length=20)),
                ('consumption_per_minute', models.IntegerField(default=10)),
                ('is_on', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConsumingObject', to='main.account')),
            ],
        ),
    ]
