# Generated by Django 4.0.2 on 2022-12-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contract_remove_tv_consumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='surplus',
            field=models.IntegerField(default=0),
        ),
    ]
