# Generated by Django 4.0.2 on 2023-02-13 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_modelreference_consumingobject_model_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumingobject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consumingobject',
            name='consumptionPerDay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000000), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='consumptionPerDay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000000), blank=True, default=[], size=None),
        ),
    ]
