# Generated by Django 4.0.2 on 2023-02-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_consumingobject_todaysconsumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumingobject',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='producingobject',
            old_name='active',
            new_name='is_active',
        ),
    ]
