# Generated by Django 4.0.2 on 2023-02-13 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_consumptionperday_consumingobject_consumption_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumingobject',
            name='expense_per_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='consumingobject',
            name='todays_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='expense_per_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='todays_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumingobject',
            name='consumption_per_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='producingobject',
            name='consumption_per_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
