# Generated by Django 4.0.2 on 2023-02-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='Object',
        ),
    ]
