# Generated by Django 4.0.2 on 2023-02-15 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_account_object_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dayly_energy_mix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='weekly_energy_mix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None), blank=True, default=list, size=None),
        ),
    ]
