# Generated by Django 4.0.2 on 2023-02-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_contract_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
    ]
