# Generated by Django 4.0.2 on 2023-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_account_energy_mix_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='private_key',
            field=models.CharField(default='', max_length=42),
        ),
    ]
