# Generated by Django 3.0 on 2023-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20230217_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='private_key',
            field=models.CharField(default='', max_length=70),
        ),
    ]
