# Generated by Django 3.0 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20230304_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_consumption',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_production',
        ),
        migrations.RemoveField(
            model_name='account',
            name='surplus',
        ),
        migrations.AddField(
            model_name='transactions',
            name='last_block',
            field=models.IntegerField(default=0),
        ),
    ]
