# Generated by Django 4.0.2 on 2022-11-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_account_number_account_is_consuming_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='address',
        ),
    ]
