# Generated by Django 4.0.2 on 2022-12-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_producingobject_heating_cooling_consumingobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heating',
            name='consumer',
        ),
        migrations.DeleteModel(
            name='Cooling',
        ),
        migrations.DeleteModel(
            name='Heating',
        ),
    ]
