# Generated by Django 4.0.2 on 2022-12-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_heating_consumer_delete_cooling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producingobject',
            old_name='consumption_per_minute',
            new_name='production_per_minute',
        ),
        migrations.AlterField(
            model_name='consumingobject',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consuming_object', to='main.account'),
        ),
        migrations.AlterField(
            model_name='producingobject',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producing_object', to='main.account'),
        ),
    ]
