# Generated by Django 4.0.2 on 2022-12-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_consumption_per_minute_producingobject_production_per_minute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producingobject',
            old_name='consumer',
            new_name='producer',
        ),
    ]
