# Generated by Django 4.0.2 on 2023-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_consumingobject_overall_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumingobject',
            name='modelReference',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consumingobject',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumingobject',
            name='room',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='modelReference',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='overall_consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='room',
            field=models.CharField(default='', max_length=50),
        ),
    ]
