# Generated by Django 4.0.2 on 2023-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_consumingobject_modelreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumingobject',
            name='overall_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='overall_expense',
            field=models.IntegerField(default=0),
        ),
    ]
