# Generated by Django 4.0.2 on 2023-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_consumingobject_name_producingobject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumingobject',
            old_name='modelReference',
            new_name='model_reference',
        ),
    ]
