# Generated by Django 4.0.2 on 2023-02-13 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_consumingobject_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumingobject',
            name='consumptionPerDay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000000), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='producingobject',
            name='consumptionPerDay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000000), blank=True, default=list, size=None),
        ),
    ]
