# Generated by Django 4.0.2 on 2023-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_consumingobject_consumptionperday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumingobject',
            name='todaysConsumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producingobject',
            name='todaysConsumption',
            field=models.IntegerField(default=0),
        ),
    ]
