# Generated by Django 4.0.2 on 2023-02-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_objects_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='is_consuming',
            new_name='is_consuming_object',
        ),
    ]
