# Generated by Django 4.0.2 on 2023-02-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_account_dayly_energy_mix_account_weekly_energy_mix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dayly_energy_mix',
            new_name='daily_energy_mix',
        ),
    ]
