# Generated by Django 4.0.2 on 2023-02-15 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_dayly_energy_mix_account_daily_energy_mix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='weekly_energy_mix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None), size=None),
        ),
    ]
