# Generated by Django 4.0.2 on 2023-02-15 18:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_account_weekly_energy_mix'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='overall_energy_mix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
