# Generated by Django 4.0.2 on 2023-02-16 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_account_overall_energy_mix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='weekly_energy_mix',
            new_name='energy_mix_per_day',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='daily_energy_mix',
            new_name='todays_energy_mix',
        ),
        migrations.AddField(
            model_name='contract',
            name='price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
            preserve_default=False,
        ),
    ]
