# Generated by Django 4.0.2 on 2023-02-16 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_weekly_energy_mix_account_energy_mix_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
