# Generated by Django 4.0.2 on 2023-02-16 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
