# Generated by Django 4.0.2 on 2023-02-16 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_contract_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='energy_mix_per_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None), blank=True, default=list, size=None),
        ),
    ]
