# Generated by Django 3.0 on 2023-03-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20230306_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testobject',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestObject',
        ),
    ]
