# Generated by Django 3.0 on 2023-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20230306_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producingobject',
            name='producer',
        ),
        migrations.AddField(
            model_name='transactions',
            name='address',
            field=models.CharField(default='', max_length=42),
        ),
        migrations.DeleteModel(
            name='ConsumingObject',
        ),
        migrations.DeleteModel(
            name='ProducingObject',
        ),
    ]
