# Generated by Django 3.0 on 2023-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20230306_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_new_user',
            field=models.BooleanField(default=False),
        ),
    ]
