# Generated by Django 3.0 on 2023-03-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_account_is_new_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address',
            new_name='eth_address',
        ),
    ]
